# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [9]:
'''
Your Code
'''
import numpy as np
print(np.zeros((2, 3)))
print(np.empty((2, 3), dtype = 'int'))

[[0. 0. 0.]
 [0. 0. 0.]]
[[5505097 5242975 4653121]
 [5374021 6488125 7602273]]


#### np.zeros建立元素都為0的陣列
#### np.empty建立元素為隨機值(尚未初始化)的陣列

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
# 記得先 Import 正確的套件

'''
Your Code
'''

In [25]:
# 參考解答

a = np.random.rand(2, 3) + 1.920929
print(a)
b = np.array(a, dtype='int')
print(b)
'''
Your Code
'''

[[2.388361   1.96262171 2.12092234]
 [2.40107733 2.29233217 2.21848245]]
[[2 1 2]
 [2 2 2]]


'\nYour Code\n'

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [28]:
m = 20
n = 40
a = np.random.rand(2, 3) + m
print(a)
'''
Your Code
'''

[[20.45715565 20.02470989 20.89186792]
 [20.76824209 20.87657893 20.09824477]]


'\nYour Code\n'