# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
'''
Your Code
'''
import numpy as np
a = np.arange(5)
print(a)
print(a.sum()) # numpy.ndarray
print(np.sum(a)) # module numpy
print(sum(a))  # module builtins

[0 1 2 3 4]
10
10
10


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [4]:
A = np.random.random((5, 5))
print(A)
print((A-A.min())/(A.max()-A.min()))
'''
Your Code
'''

[[0.01595428 0.71232314 0.40347903 0.81035121 0.07998433]
 [0.49289331 0.25645411 0.17715123 0.82695518 0.04567058]
 [0.03167518 0.16326998 0.97301136 0.98804918 0.5114532 ]
 [0.3434889  0.94171156 0.48075372 0.63598165 0.9443111 ]
 [0.3565875  0.95571819 0.24371381 0.71031549 0.49044528]]
[[0.         0.71635893 0.3986491  0.81720101 0.0658681 ]
 [0.49063011 0.24740365 0.1658243  0.83428162 0.03056934]
 [0.01617219 0.15154457 0.9845305  1.         0.50972279]
 [0.33693688 0.95233221 0.47814205 0.63782597 0.95500637]
 [0.3504115  0.96674092 0.23429763 0.71429365 0.48811182]]


'\nYour Code\n'

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [5]:
A = np.arange(10)
print(A)
A[A.max()] = -1
print(A)
'''
Your Code
'''

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8 -1]


'\nYour Code\n'