# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 記得先 Import 正確的套件
import numpy as np
'''
Your Code
'''

'\nYour Code\n'

In [19]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print(Z)

[[[3 7 1 ... 7 3 7]
  [3 5 8 ... 1 5 1]
  [3 5 4 ... 9 6 3]
  ...
  [3 4 1 ... 0 6 7]
  [2 6 3 ... 5 8 4]
  [0 7 1 ... 4 5 1]]

 [[1 8 2 ... 1 4 7]
  [0 4 1 ... 1 5 6]
  [0 9 7 ... 0 6 7]
  ...
  [6 6 6 ... 0 1 4]
  [8 0 9 ... 4 7 2]
  [7 9 1 ... 7 3 9]]

 [[3 1 9 ... 1 0 8]
  [3 9 5 ... 7 7 5]
  [9 9 7 ... 7 3 0]
  ...
  [3 5 4 ... 8 2 2]
  [4 5 6 ... 8 2 9]
  [6 3 8 ... 4 3 7]]

 ...

 [[3 6 4 ... 1 4 5]
  [2 4 8 ... 6 4 0]
  [7 0 1 ... 6 9 2]
  ...
  [4 9 8 ... 5 0 5]
  [2 2 4 ... 3 8 4]
  [5 2 2 ... 4 6 1]]

 [[6 9 1 ... 4 5 1]
  [3 1 5 ... 0 4 0]
  [8 5 1 ... 1 9 8]
  ...
  [3 8 5 ... 0 9 5]
  [5 3 7 ... 8 2 7]
  [8 0 1 ... 4 9 4]]

 [[9 6 4 ... 7 4 6]
  [0 8 8 ... 3 3 2]
  [6 8 0 ... 4 0 2]
  ...
  [2 4 3 ... 2 0 2]
  [2 7 3 ... 5 8 1]
  [8 0 0 ... 2 0 2]]]


In [26]:
%timeit -n 10 a = 2
for i in Z:
    for j in i:
        for k in j:
            i=i+1
'''
Your Code
'''

32.9 ns ± 15.8 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


'\nYour Code\n'

In [24]:
%timeit -n 10 a = 2
for i in Z.flat:
    i=i+1
'''
Your Code
'''

27.1 ns ± 10.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


'\nYour Code\n'

In [23]:
%timeit -n 10 a = 2
for i in np.nditer(Z):
    i=i+1
'''
Your Code
'''

31.4 ns ± 8.33 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


'\nYour Code\n'

### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [13]:

Z = np.random.randint(0,10,50)
print(Z)


[7 0 6 6 5 8 3 7 5 1 9 4 7 6 3 6 9 7 9 8 5 2 0 6 0 2 0 4 4 8 8 8 8 0 8 2 2
 3 4 4 6 1 9 0 2 0 1 3 6 3]


In [14]:
print(np.bincount(Z).max())
'''
Your Code
'''

7


'\nYour Code\n'

In [17]:
print(np.where(Z == np.bincount(Z).max()))
'''
Your Code
'''

(array([ 0,  7, 12, 17], dtype=int64),)


'\nYour Code\n'

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [29]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[5, 9, 2, 4, 1, 0]
[5, 9, 2, 4, 1, 0]
[[8, 6, 3, 1], [3, 4, 1, 6], [0, 9, 3, 6]]
[array([8, 6, 3, 1]), array([3, 4, 1, 6]), array([0, 9, 3, 6])]
[[[8, 0], [1, 1], [3, 5]], [[1, 2], [8, 6], [6, 7]]]
[array([[8, 0],
       [1, 1],
       [3, 5]]), array([[1, 2],
       [8, 6],
       [6, 7]])]


In [30]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))
'''
Your Code
'''

[5, 9, 2, 4, 1, 0]
[[8, 6, 3, 1], [3, 4, 1, 6], [0, 9, 3, 6]]
[[[8, 0], [1, 1], [3, 5]], [[1, 2], [8, 6], [6, 7]]]


'\nYour Code\n'