# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [5]:
# 記得先 Import 正確的套件
import numpy as np
a = np.arange(11)
a[3:8] = a[3:8]*-1
print(a)
'''
Your Code
'''

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


'\nYour Code\n'

In [8]:
'''
Your Code
'''

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [9]:
A = np.random.rand(3, 6)
print(A)
print(len(A[A > 0.5]))
'''
Your Code
'''

[[0.6758791  0.37502415 0.88422735 0.90349716 0.44711904 0.31217377]
 [0.80491817 0.10858696 0.36554024 0.5000756  0.14490894 0.33798961]
 [0.73464727 0.66087755 0.08841741 0.30284393 0.48667583 0.02630007]]
7


'\nYour Code\n'