# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [4]:
import numpy as np
a = np.arange(15).reshape(3,5)
'''
Your Code
list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；

tolist() 才能達成多層的型態轉換。
'''
test = list(a)
print(test[0])
print(type(test[0]))

test1 = a.tolist()
print(test1[0])
print(type(test1[0]))

[0 1 2 3 4]
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4]
<class 'list'>


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [5]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [12]:

a = np.random.randint(10, size=6) 

'''
Your Code
'''
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[1 2 8 3 0 5]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [13]:
b = np.random.randint(10, size=(3,4)) 

'''
Your Code
'''
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[4 7 9 8]
 [9 4 0 8]
 [0 2 7 1]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [14]:
c = np.random.randint(10, size=(2,3,2)) 

'''
Your Code
'''
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[8 7]
  [3 6]
  [5 5]]

 [[3 3]
  [0 8]
  [0 2]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### ndim: 變數的維度
### shape: 變數中每個維度的大小
### size: 變數裡面所包含的元素總個數
### dtype: 變數裡面所儲存的元素型態
### itemsize: 變數裡面元素所佔的記憶體大小
### length: 變數的長度
### type: 變數的型態

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [35]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))
a.ndim

[3, 1, 3, 1, 6, 1]
[3, 1, 3, 1, 6, 1]


1

In [16]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[8, 9, 4, 5], [6, 4, 9, 2], [0, 7, 6, 8]]
[array([8, 9, 4, 5]), array([6, 4, 9, 2]), array([0, 7, 6, 8])]


In [31]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))
print(c[0][0][0])

[[[9, 0], [9, 2], [6, 8]], [[8, 3], [4, 8], [5, 3]]]
[array([[9, 0],
       [9, 2],
       [6, 8]]), array([[8, 3],
       [4, 8],
       [5, 3]])]
9


In [39]:
def tolist(iterable):
    '''
    Your Code
    '''
    result = list(iterable)
    if (iterable.ndim == 1):
        return result
    
    for i in range(len(result)):
        result[i] = tolist(result[i])
        
    return result
        
    
        

print(tolist(a))
print(tolist(b))
print(tolist(c))

[3, 1, 3, 1, 6, 1]
[[8, 9, 4, 5], [6, 4, 9, 2], [0, 7, 6, 8]]
[[[9, 0], [9, 2], [6, 8]], [[8, 3], [4, 8], [5, 3]]]
