In [1]:
import numpy as np

In [2]:
array1 = np.array([[10, 8], [3,5]])

In [ ]:
#1

In [5]:
print(np.dot(np.linalg.inv(array1), array1))

[[1. 0.]
 [0. 1.]]


In [6]:
#Ans: 是

In [7]:
#2

In [8]:
eigenvalue, eigenvector = np.linalg.eig(array1)

In [11]:
print(eigenvalue, '\n', eigenvector)

[13.  2.] 
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [12]:
#3

In [13]:
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))